version: '3'

services:
  app:
    build: .
    environment:
      USER_NAME: postgres
      PASSWORD: postgres
      HOST_NAME: db
    volumes:
      - api-data:/tmp/api-data

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/share/nginx/static
      - ./media:/usr/share/nginx/media
      - api-data:/tmp/api-data
    ports:
      - 80:80

volumes:
  postgres-data:
  api-data:
